app = "delicate-shape-1974"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "vaultwarden/server:alpine"

[experimental]
  auto_rollback = true

[env]
  # https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
  ADMIN_RATELIMIT_SECONDS = "10"
  ADMIN_SESSION_LIFETIME = "10"
  INVITATIONS_ALLOWED = "false"
  IP_HEADER = "X-Forwarded-For"
  LOGIN_RATELIMIT_MAX_BURST = "3"
  LOGIN_RATELIMIT_SECONDS = "10"
  PASSWORD_ITERATIONS = "2000000"
  SHOW_PASSWORD_HINT = "false"
  SIGNUPS_ALLOWED = "false"
  SIGNUPS_VERIFY = "true"
  SMTP_HOST = "email-smtp.eu-west-1.amazonaws.com"
  SMTP_PORT = "465"
  SMTP_SECURITY = "force_tls"
  WEBSOCKET_ENABLED = "false"
  LOG_LEVEL = "off"
  # DOMAIN=flyctl secrets
  # SMTP_FROM=flyctl secrets
  # SMTP_PASSWORD=flyctl secrets
  # SMTP_USERNAME=flyctl secrets
  # password; echo -n "<password>" | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4
  # or
  # password_argon2
  # ADMIN_TOKEN=flyctl secrets
  PUSH_ENABLED=true
  # PUSH_INSTALLATION_ID=flyctl secrets
  # PUSH_INSTALLATION_KEY=flyctl secrets

[[mounts]]
  source = "vaultwarden_data_machines"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    tls_options = { "alpn" = ["h2", "http/1.1"], "versions" = ["TLSv1.2", "TLSv1.3"] }

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
