app = "delicate-shape-1974"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "vaultwarden/server:latest"

[mounts]
  source = "vaultwarden_data"
  destination = "/data"

[env]
  SIGNUPS_ALLOWED=false
  INVITATIONS_ALLOWED=false
  SHOW_PASSWORD_HINT=false
  WEBSOCKET_ENABLED=true
  SMTP_HOST="smtp.gmail.com"
  SMTP_PORT=587
  SMTP_SECURITY="starttls"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

